import type { Metadata } from "next";
import { Happy_Monkey } from 'next/font/google';
import Providers from "@/modules/Providers/providers";
import { CartProvider } from "@/lib/CartContext/CartContext";
import { RegionProvider } from "@/lib/RegionContext/RegionContext";


import "./globals.css";

import Box from '@mui/material/Box'




import NavBar from "@/modules/Nav/NavigationMenu";




const happyMonkey = Happy_Monkey({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-happy-monkey', // Custom CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={happyMonkey.className}>
      <body>

        <Providers>

          <RegionProvider>

            <CartProvider>

              <Box
              sx={{
                width: '100%',
                maxWidth: { 
                  xs: '100%',        // Mobile: full width
                  sm: 600,           // Tablet: 600px
                  md: 900,           // Small desktop: 900px
                  lg: 1200,          // Medium desktop: 1200px
                  xl: 1440           // Large screens: 1440px
                },
                mx: 'auto',
                px: { xs: 0, sm: 0 } // Responsive padding
              }}
              border={{
                xs: '2px solid red',
                sm: '2px solid green',
                md: '2px solid purple',
                lg: '2px solid brown',
                xl: '2px solid purple'
              }}>

                <NavBar />
                
                {children}

              </Box>

            </CartProvider>

          </RegionProvider>



        </Providers>



      </body>
    </html>
  );
}
