import type { Metadata } from "next";
import { Poppins, Happy_Monkey } from 'next/font/google';
import Providers from "@/lib/Providers/providers";

import "./globals.css";



import NavBar from "@/modules/Nav/NavigationMenu";


const poppins = Poppins({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

const happyMonkey = Happy_Monkey({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-happy-monkey', // Custom CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={happyMonkey.className}>
      <body>

        <Providers>

            <NavBar />
            
            {children}

        </Providers>



      </body>
    </html>
  );
}
